base_url: http://127.0.0.1:8080

endpoints:
  - path: /
    method: GET
    description: Home Page
    iteration: 1000

  - path: /contact
    method: GET
    description: Contact Page
    iteration: 150





